apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx-rs-container
        ports:
        - containerPort: 80
